language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - pip install coverage coveralls flake8 flask pillow

# command to run tests
script: 
  - coverage run --source=flask_avatars setup.py test
  - flake8 flask_avatars test_flask_avatars.py

after_success: coveralls
